export const producs = [
  [
    {
      image: require('../assets/images/bliss.png'),
      name: 'Шоколадный Блисс',
      description: 'Нежный шоколадный бисквит с кремом из темного шоколада.',
      price: 35,
      count: 1,
    },
    {
      image: require('../assets/images/vanil.png'),
      name: 'Ванильное Облако',
      description: 'Легкий ванильный бисквит с крем-чизом и ягодами.',
      price: 40,
      count: 1,
    },
    {
      image: require('../assets/images/ray.png'),
      name: 'Карамельный Рай',
      description: 'Многослойный карамельный торт с ореховыми крошками.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/images/sad.png'),
      name: 'Фруктовый Сад',
      description: 'Светлый бисквит с фруктовым желе и свежими фруктами.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/images/tiramisu.png'),
      name: 'Тирамису',
      description: 'Слоеный пирог с ягодами и сливочным кремом.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/images/shtrudel.png'),
      name: 'Ягодный Штрудель',
      description:
        'Традиционный итальянский десерт с маскарпоне и кофейным вкусом.',
      price: 15,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/images/malina.png'),
      name: 'Малиновое',
      description: 'Ванильный капкейк с малиновым кремом.',
      price: 35,
      count: 1,
    },
    {
      image: require('../assets/images/limon.png'),
      name: 'Лимонный Рассвет',
      description: 'Нежный лимонный капкейк с лимонной цедрой.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/images/orex.png'),
      name: 'Ореховый Сюрприз',
      description: 'Шоколадный капкейк с ореховой начинкой.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/images/vanill.png'),
      name: 'Ванильный',
      description: 'Простой ванильный капкейк с белым кремом.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/images/utro.png'),
      name: 'Кофейное Утро',
      description: 'Капкейк с кофейным вкусом и шоколадным кремом.',
      price: 40,
      count: 1,
    },
    {
      image: require('../assets/images/chudo.png'),
      name: 'Карамельное Чудо',
      description: 'Капкейк с карамельным вкусом и карамельной начинкой.',
      price: 15,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/images/strast.png'),
      name: 'Шоколадная Страсть',
      description: 'Шоколадные макаруны с нежным кремом.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/images/destvo.png'),
      name: 'Ванильное детство',
      description: 'Ванильные макаруны с кремовой начинкой.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/images/son.png'),
      name: 'Лавандовый Сон',
      description: 'Макаруны с ароматом лаванды и лимонным кремом.',
      price: 25,
      count: 1,
    },
    {
      image: require('../assets/images/probujdeniye.png'),
      name: 'Кофейное Пробуждение',
      description: 'Макаруны с кофейным вкусом и шоколадной начинкой.',
      price: 45,
      count: 1,
    },
    {
      image: require('../assets/images/rassvet.png'),
      name: 'Малиновый Рассвет',
      description: 'Малиновые макаруны с кремовой начинкой.',
      price: 30,
      count: 1,
    },
    {
      image: require('../assets/images/vixr.png'),
      name: 'Карамельный Вихрь',
      description: 'Карамельные макаруны с соленой карамелью.',
      price: 25,
      count: 1,
    },
  ],

  [
    {
      image: require('../assets/images/espresso.png'),
      name: 'Эспрессо',
      description: 'Интенсивный и ароматный.',
      price: 5,
      count: 1,
    },
    {
      image: require('../assets/images/latte.png'),
      name: 'Латте Макиато',
      description: 'Мягкий и кремовый, с легким вкусом кофе.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/images/americano.png'),
      name: 'Американо',
      description: 'Классический, крепкий кофе с водой.',
      price: 5,
      count: 1,
    },
    {
      image: require('../assets/images/mokacino.png'),
      name: 'Мокачино',
      description: 'Шоколадный кофейный напиток с взбитыми сливками.',
      price: 20,
      count: 1,
    },
    {
      image: require('../assets/images/smuzi.png'),
      name: 'Фруктовый Смузи',
      description: 'Натуральный смузи из сезонных фруктов.',
      price: 15,
      count: 1,
    },
    {
      image: require('../assets/images/capucino.png'),
      name: 'Капучино',
      description: 'Пенный и насыщенный, с балансом молока и кофе.',
      price: 10,
      count: 1,
    },
  ],
];
